### ISSUE TITLE
Please do not use Hacked servers as a repo

### ISSUE THREAD

**Issue by nitantsoni** [kuruoujou/kuroshi-xbmc-repo#3]
curl -I http://ramblingahoge.net/
HTTP/1.1 301 Moved Permanently
Date: Wed, 07 Jun 2017 00:02:30 GMT
Content-Type: text/html
Connection: keep-alive
Set-Cookie: __cfduid=de22fefa2924439efd775ae57fe67b1081496793749; expires=Thu, 07-Jun-18 00:02:29 GMT; path=/; domain=.ramblingahoge.net; HttpOnly
Location: http://jistudio.net/
X-FW-Hash: x4xx6ihnc4
X-FW-Serve: TRUE
X-Cache: HIT
X-Hits: 2
X-FW-Static: NO
X-FW-Type: VISIT
Server: cloudflare-nginx
CF-RAY: 36af57c856b61ebf-SJC

**Comment by kuruoujou** [comment]
Heh. I didn't think anyone still used this, so I turned off the server, or
so I thought. I just haven't updated the root domain so I figure the IP got
reassigned. I'll take care of this later this evening, thanks for the
report.

If you would like to take over the responsibility for this and the plugin,
please let me know. I've switched completely over to Plex so I stopped
developing this plugin. I'm instead working (quite slowly) on a generic api
front end for things like mal, anilist, and trakt, with the intent for it
to work primarily with Plex webhooks.

At the rate I'm going though I won't have it out for probably months.

Anyway, thank you for the report, I'll update this issue once I'm at a
computer and have taken care of it.

**Comment by kuruoujou** [comment]
I have removed the A record for ramblingahoge.net, but it will take a bit to propagate.

**Comment by nitantsoni** [comment]
Thanks a ton!! Didn't realize this was in error.
